### ISSUE TITLE
Set webhook url per session?

### ISSUE THREAD

**Issue by thiago28x** [chrishubert/whatsapp-api#103]
Hello, thanks for putting this together, and sorry my dumb questions below (Im more used to "MyZap api").

If I understand correctly, the webhook url is stored in the .env, and there is no endpoint or way to update the .env webhook urls while the node app is running, right? 

I ask this because my use case is several clients with unique, optional, webhook urls, as its used in MyZap and some others...

For now my osha solution is to route every client to BASE_WEBHOOK_URL, and then re-route them again individually, unless Im missing something as big as a house?

**Comment by avoylenko** [comment]
There is no way to change the webhook on fly, but you can define an individual webhook per session. 

https://github.com/chrishubert/whatsapp-api/blob/21a714f1dbf4971ba0b9b74dd58c75d1082edbc8/README.md?plain=1#L145
