### ISSUE TITLE
Prod Deployment issue 

### ISSUE THREAD

**Issue by logiversetechnologies** [chrishubert/whatsapp-api#106]
After deployed prod it is not working always give you 

{
  "success": false,
  "message": "qr code not ready or already scanned"
}

**Comment by avoylenko** [comment]
The error says that session is already authorized to login or QR code is not ready on the page. Wipe the session storage folder and restart the service or check the your server is allowed to access the internet.

**Comment by mdestafadilah** [comment]
this is not code issue, this your server issue, please close. this issue.

**Comment by chrishubert** [comment]
Closing for lack of update, feel free to re-open if needed
