### ISSUE TITLE
ask for info about starting to scan qr code

### ISSUE THREAD

**Issue by Alkhazrajy** [chrishubert/whatsapp-api#113]
Hello, 
I tried to start a new session by using the endpoint http://localhost:3000/session/qr/:sessionId/image/, 
the response returned {"success":false,"error":"Session should be alphanumerical or -"},
could you please tell me how can I start a new session an save it ?
thank you in advance,

**Comment by avoylenko** [comment]
You are using a wrong endpoint to start a new session.  To start the session send the GET request to the `http://localhost:3000/session/start/ABCD` endpoint.

**Comment by mdestafadilah** [comment]
1. You must create a session, you can try with `/session/start/{sessionId}` endpoint. make sure your session is **alphanumerical**.
2. Generate your Qrcode with `/session/qr/{sessionId}/image` endpoint.
3. Then, linked device in Whatsapp phone to scan the Qr.

for remember, this is use pupputer, make sure your installed all ready in your server.

**Comment by hiahiahiawow** [comment]
> 1. You must create a session, you can try with `/session/start/{sessionId}` endpoint. make sure your session is **alphanumerical**.
> 2. Generate your Qrcode with `/session/qr/{sessionId}/image` endpoint.
> 3. Then, linked device in Whatsapp phone to scan the Qr.
> 
> for remember, this is use pupputer, make sure your installed all ready in your server.

1. I create a session like that :http://localhost:3000/session/start/1qaz2wsx3edc, and response is :{"success":false,"error":"Invalid API key"}

**Comment by hiahiahiawow** [comment]
http://localhost:3000/session/start/1qaz2wsx3edc   returns:{"success":false,"error":"Invalid API key"}
what shoud I do befor all start? must generate x-api-key? but I don't know how to generate x-api-key.
help & tks

**Comment by mdestafadilah** [comment]
> http://localhost:3000/session/start/1qaz2wsx3edc returns:{"success":false,"error":"Invalid API key"} what shoud I do befor all start? must generate x-api-key? but I don't know how to generate x-api-key. help & tks

.env file look at example, it's mine

```bash
## Application ##
PORT=3005 # OPTIONAL, DEFAULT 3000
API_KEY= # OPTIONAL, DEFAULT EMPTY
BASE_WEBHOOK_URL=http://localhost:3005/localCallbackExample # MANDATORY
ENABLE_LOCAL_CALLBACK_EXAMPLE=FALSE # OPTIONAL, DISABLE FOR PRODUCTION
RATE_LIMIT_MAX=1000 # OPTIONAL, THE MAXIUM NUMBER OF CONNECTIONS TO ALLOW PER TIME FRAME
RATE_LIMIT_WINDOW_MS=1000 # OPTIONAL, TIME FRAME FOR WHICH REQUESTS ARE CHECKED IN MS

## Client ##
MAX_ATTACHMENT_SIZE=10000000 # IF REACHED, MEDIA ATTACHMENT BODY WILL BE NULL
SET_MESSAGES_AS_SEEN=TRUE # WILL MARK THE MESSAGES AS READ AUTOMATICALLY
# ALL CALLBACKS: auth_failure|authenticated|call|change_state|disconnected|group_join|group_leave|group_update|loading_screen|media_uploaded|message|message_ack|message_create|message_reaction|message_revoke_everyone|qr|ready|contact_changed|media
DISABLED_CALLBACKS=message_ack|message_reaction  # PREVENT SENDING CERTAIN TYPES OF CALLBACKS BACK TO THE WEBHOOK
WEB_VERSION='2.2328.5' # OPTIONAL, THE VERSION OF WHATSAPP WEB TO USE
WEB_VERSION_CACHE_TYPE=none # OPTIONAL, DETERMINTES WHERE TO GET THE WHATSAPP WEB VERSION(local, remote or none), DEFAULT 'none'
RECOVER_SESSIONS=TRUE # OPTIONAL, SHOULD WE RECOVER THE SESSION IN CASE OF PAGE FAILURES

## Session File Storage ##
SESSIONS_PATH=./sessions # OPTIONAL

ENABLE_SWAGGER_ENDPOINT=TRUE # OPTIONAL
```

**Comment by muava12** [comment]
if i use api key, how to start new session using api key? where do i should put the api key? in url?

**Comment by avoylenko** [comment]
@muava12 the api key should be in the **x-api-key** header

**Comment by chrishubert** [comment]
Closing as completed
