### ISSUE TITLE
Not send buttons and list

### ISSUE THREAD

**Issue by oswaldo-ore** [chrishubert/whatsapp-api#114]
Hello, because in my normal WhatsApp sending buttons and sending lists does not work.

**Comment by avoylenko** [comment]
Buttons and Lists are blocked by WhatsApp.  If you want to have them - switch to official meta api.

**Comment by mdestafadilah** [comment]
have you try pairing whatsapp business in smarthphone?

**Comment by chrishubert** [comment]
Correct, the buttons are still not supported until now.
