### ISSUE TITLE
Is On Whatsapp?	

### ISSUE THREAD

**Issue by mdestafadilah** [chrishubert/whatsapp-api#115]
it's missing REST API or DOC?

**Comment by mdestafadilah** [comment]
in readme file, in features, i see API and Callbacks has a feature *Is on Whatsapp* but when i see in [clientController](https://github.com/chrishubert/whatsapp-api/blob/master/src/controllers/clientController.js#L22) 
> https://github.com/chrishubert/whatsapp-api#features

am i missing read the file of doc, or may this code actually never created?

**Comment by avoylenko** [comment]
@mdestafadilah you are looking for the '/getNumberId/:sessionId' endpoint. You need to post a phone number and it returns the WhatsApp ID if is the user is registered.

https://docs.wwebjs.dev/Client.html#getNumberId

**Comment by mdestafadilah** [comment]
yes. it's too long response. it's GET or POST actually? and, i need check other number, not own number has been pairing.

**Comment by avoylenko** [comment]
@mdestafadilah it's a POST request where you have to submit the payload with the requested number. The format is below:
`{ "number": "12345@c.us"}`

**Comment by avoylenko** [comment]
@mdestafadilah new rest endpoints were added with better swagger specification. The document is here [swagger.json](https://github.com/chrishubert/whatsapp-api/blob/master/swagger.json)

**Comment by mdestafadilah** [comment]
Nice, thanks @avoylenko !! your work is amazing. i will try yesterday.

**Comment by mdestafadilah** [comment]
I've done tested, and it's work good. i will close. thanks @avoylenko and @chrishubert !!.
