### ISSUE TITLE
Add a contact

### ISSUE THREAD

**Issue by Lyfhael** [chrishubert/whatsapp-api#116]
Hey,

I'm looking to know if a phone number is in-use on Whatsapp and get their profile picture. I can do that on my phone but I've been interested to know if it's possible with your library ?
I've looked at your swagger.json but I don't think I'm seeing something related. I did see /client/getProfilePicUrl/{sessionId} but I'm guessing anything starting with /client/ is for our account and not someone else account so I can't use it to lookup someone else profile's picture.

Something that seems like it could be what I'm looking for in your README, is "Is On Whatsapp ?" feature, however I'm not seeing something anything about it in the swagger.json

**Comment by avoylenko** [comment]
Hello. It's been implemented, the new endpoints were added to get the picture of the contact and get users registration status on whatsapp, so I awaiting until @chrishubert approves the PR.

**Comment by avoylenko** [comment]
New endpoints were added to eliminate the confusion. The `/client/isRegisteredUser/{sessionId}` endpoint should be used to check if a phone number is in-use on Whatsapp and the `/client/getProfilePicUrl/{sessionId}` or `/contact/getProfilePicUrl/{sessionId}` to get the profile picture url of a phone number.

**Comment by Lyfhael** [comment]
> New endpoints were added to eliminate the confusion. The `/client/isRegisteredUser/{sessionId}` endpoint should be used to check if a phone number is in-use on Whatsapp and the `/client/getProfilePicUrl/{sessionId}` or `/contact/getProfilePicUrl/{sessionId}` to get the profile picture url of a phone number.

Thank you very much
