### ISSUE TITLE
"error": "Invalid API key" 

### ISSUE THREAD

**Issue by eduardohr-muniz** [chrishubert/whatsapp-api#118]
![image](https://github.com/chrishubert/whatsapp-api/assets/90477293/767eaed7-c1af-4b8d-b863-63d5ea8425e2)

I have this problem, could you explain to me what I'm doing wrong?

**Comment by avoylenko** [comment]
@eduardohr-muniz you have defined you api key as `EMTPY`, thats why the service is awaiting to receive it in the `x-api-key` header

**Comment by eduardohr-muniz** [comment]
I corrected it here, it worked, thank you very much!
