### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by eduardohr-muniz** [chrishubert/whatsapp-api#120]
I was testing the api today, I thought it was really cool, congratulations, I would like to ask a question in case I can't send the buttons, am I doing something wrong or it still doesn't work? my wpp is business
![image](https://github.com/chrishubert/whatsapp-api/assets/90477293/93304c33-78b3-45cf-b8d0-4e8978d58177)

**Comment by avoylenko** [comment]
As far I know, there are no ways to send buttons or lists using whastapp web page at this moment, but I have never tried to send them. See https://github.com/pedroslopez/whatsapp-web.js/issues/2316

**Comment by chrishubert** [comment]
Correct, the buttons are still not supported until now.
