### ISSUE TITLE
Get User Bio ?

### ISSUE THREAD

**Issue by Lyfhael** [chrishubert/whatsapp-api#121]
Hi,
Is it posssible through a contactId that we haven't chatted with, get their Bio ?
On web.whatsapp.com when I search for a new phone number, that I check their profile, sometime I can see this : 
![FWqXQvg](https://github.com/chrishubert/whatsapp-api/assets/43145883/3fbc4ce1-cc8f-41b8-ad8d-ec00d562d351)

I did try :

curl -X POST http://localhost:3000/contact/getAbout/ABCD \
     -H "Content-Type: application/json" \
     -d '{"contactId": "{phone}@c.us"}'

I get: {"success":true,"result":{}}
(nothing in the result property)

Thank you !

**Comment by avoylenko** [comment]
You are using the right api method to get the info. Not sure why it's empty in your case. Have you tried to do the same for another contact?

**Comment by Lyfhael** [comment]
> web.whatsapp.com when I search for a new phone number



> You are using the right api method to get the info. Not sure why it's empty in your case. Have you tried to do the same for another contact?

Yes I tried multiple

**Comment by avoylenko** [comment]
Are you sure that you are on the latest docker image?

**Comment by mdestafadilah** [comment]
it's working for non-docker. i'm tested.

**Comment by avoylenko** [comment]
It this case pull the latest image from the docker hub.
