### ISSUE TITLE
Error Route /message/getInfo

### ISSUE THREAD

**Issue by brunoxtrindade** [chrishubert/whatsapp-api#129]

**Comment by brunoxtrindade** [comment]
I receive this error 
{
    "success": false,
    "error": "Evaluation failed: TypeError: Cannot read properties of undefined (reading 'sendQueryMsgInfo')\n    at __puppeteer_evaluation_script__:5:51"
}

**Comment by avoylenko** [comment]
Already fixed in https://github.com/pedroslopez/whatsapp-web.js/pull/2574. Awaiting new whatsapp-web.js library release.
