### ISSUE TITLE
How to get x-api-key value for Available authorizations

### ISSUE THREAD

**Issue by hiahiahiawow** [chrishubert/whatsapp-api#131]
Befor all start it must generate x-api-key，but I don't know how to generate x-api-key.

**Comment by avoylenko** [comment]
The API key is defined by setting the **API_KEY** environment variable.

**Comment by hiahiahiawow** [comment]
echo $API_KEY
1qaz2wsx3edc
curl http://localhost:3000/session/start/1qaz2wsx3edc
{"success":false,"error":"Invalid API key"}

**Comment by avoylenko** [comment]
`curl -H "x-api-key: 1qaz2wsx3edc" http://localhost:3000/session/start/sessionName`

**Comment by hiahiahiawow** [comment]
> `curl -H "x-api-key: 1qaz2wsx3edc" http://localhost:3000/session/start/sessionName`
nice，tks
