### ISSUE TITLE
How to Send pdf 

### ISSUE THREAD

**Issue by logiversetechnologies** [chrishubert/whatsapp-api#135]
{
  "chatId": "XXXXXXXXX@c.us",
  "contentType": "string",
  "content": "Hello World!",
  "options": {
    "media": {
      "mimetype": "application/pdf",
"filename": "Hello Boy",
"data":""
    
    }
  }
}l

i am using this code but filename going null

**Comment by abdorag** [comment]
Hi @logiversetechnologies ,
You can use MessageMedia or MessageMediaFromUrl, It's all inside the swagger collection as examples in the method sendMessage 
if you try to send only pdf with no Intentionto send caption with it this will be file for you if you try to send caption with pdf I think there is no way to do that right now 
{
  "chatId": "xxxxxxxxxxxx@c.us",
  "contentType": "MessageMedia",
  "content": {
    "mimetype": "application/pdf",
    "data": "base64File",
    "filename": "filename.pdf"
    }
}

I hop this comment help you

**Comment by augustosnk12** [comment]
In my case, I parsed the pdf file to an array of bytes and then parsed it to a base64 this way

`pdfInArrayOfBytes.toString('base64')`

**Comment by amolood** [comment]
{
    "chatId": "XXXXXXXX@c.us",
    "contentType": "MessageMedia",
    "content": {
        "mimetype": "application/pdf",
        "data": "Base64 data",
        "filename": "filename.pdf"
    },
    "options": {
        "caption": "test"
    }
}
