### ISSUE TITLE
Webhook for message recieved

### ISSUE THREAD

**Issue by FahadAltaf** [chrishubert/whatsapp-api#136]
Can we also call a webhook on new message recieved

**Comment by avoylenko** [comment]
The webhook is being called when a new message received. Can you elaborate?

**Comment by FahadAltaf** [comment]
I have added the webhook URL in the .env file but it's not getting called
![whatsapp](https://github.com/chrishubert/whatsapp-api/assets/5881092/43054950-7896-4485-b4e7-250410d0e5a1)

**Comment by avoylenko** [comment]
The **ENABLE_LOCAL_CALLBACK_EXAMPLE** env is used for testing and demo proposes only. You should remove it from the .env file.
