### ISSUE TITLE
How to send generated qr code to front?

### ISSUE THREAD

**Issue by augustosnk12** [chrishubert/whatsapp-api#138]
Hello there,

First of all, thank you for this great lib. It's saving my life!

Secondly, I'm having some issue in sending qr code to my frontend app. This lib generate both an image and a string.
I tried to parse the string as recommended in the issues #77 and #57 , but when I try to scan to WhatsApp it does not work, I just can't connect. If I scan the qr code generated by the image resource, it does work very well, but I don't have any idea how to send this last one to my frontend. 

One way I could display the qr code in my frontend was paste all endpoint in the `src` of my `img` element:
`img src="localhost:3000/session/qr/{sessionId}/image" />` . Otherwise, I don't know if this is a good practice...

So, I would appreciate some help, or may I be doing something wrong...

**Comment by avoylenko** [comment]
Hello. The QR code is being refreshed every 20 seconds. You might see and scan the invalid QR code on you frontend side.

**Comment by augustosnk12** [comment]
For some reason it's working now...

Anyaway, thank you all 😌
