### ISSUE TITLE
Change body in triggerWebhook function

### ISSUE THREAD

**Issue by augustosnk12** [chrishubert/whatsapp-api#141]
Hello there!

This lib has a webhook calling and it works very perfectly! But I'm using the Slack webhook, and in my case it's body is `text`. In order to work I had to change the function to this

```
const triggerWebhook = (webhookURL, sessionId, dataType, data) => {
  axios.post(webhookURL, {  text: JSON.stringify(data) }, { headers: { 'x-api-key': globalApiKey } })
    .catch(error => console.error('Failed to send new message webhook:', sessionId, dataType, error.message, data))
}
```

So, I would like to not create my own branch of the project. So, is there a way to change this function in order to pass a flag or something like that?

**Comment by avoylenko** [comment]
There is no way to change the webhook payload, in your case it's better to have a simple express application to do so.

**Comment by augustosnk12** [comment]
Okay. Thanks 🥰
