### ISSUE TITLE
Set Different Webhook Each Session

### ISSUE THREAD

**Issue by imoclub** [chrishubert/whatsapp-api#142]
Hi how to set webhook not on global env? i want to add different webhook when create new session

![image](https://github.com/chrishubert/whatsapp-api/assets/59916375/e25de4eb-c787-4e54-bcda-996f25607114)

**Comment by avoylenko** [comment]
There are no ways do it, you have to create a new session and use it's session id to define the env with custom webhook for it.

**Comment by chrishubert** [comment]
Agreed with @avoylenko, this would require to create a bridge on your side to handle that situation. 
There are so many edge cases that could happen, it's not in the roadmap for now
