### ISSUE TITLE
Receiving messages?

### ISSUE THREAD

**Issue by PtolemyIV** [chrishubert/whatsapp-api#146]
Thanks for the efforts on this - very simple to set up and works great for sending messages... Is there any ability to receive messages from particular chats implemented?

Reason being would be cool to be able to have an alternative home assistant bot-style interface through a private whatsapp group

Not sure if related but the web api server shows a number of 429 error messages such as:
`Failed to send new message webhook: [session ID] message_reaction Request failed with status code 429 {
  reaction: Reaction {
    id: {
      fromMe: false,
      remote: '[chat]',
      id: '[deleted]',
      _serialized: 'false_[deleted]'
    },
    orphan: 0,
    orphanReason: undefined,
    timestamp: 1697966319.551,
    reaction: '🙏',
    read: true,
    msgId: {
      fromMe: true,
      remote: '[chat]',
      id: '[deleted]',
      _serialized: '[deleted]'
    },
    senderId: '[id]',
    ack: undefined
  }
}`

**Comment by chrishubert** [comment]
Hello @PtolemyIV, it is possible, you will by default receive a callback for all the messages and on your backend you would have to sort out the messages that are coming from that specific group (**************@g.us)

The second part is unrelated, WWeb is spamming `message_reaction` type and it is hitting the rate limiting of this repo.
You can either filter out the `message_reaction` type in your ,env file or adjust the rate limiting parameters in the .env file

**Comment by PtolemyIV** [comment]
So I shouldn't expect to see the callback messages flowing through the logs?

Any example of format to hand? In case I can try to configure it manually from home assistant since the integration I am using I don't think supports that

Thx for quick response!

**Comment by chrishubert** [comment]
The "flood" of reactions is expected at first launch of the session, nothing to worry about.
Regarding the home assistant, I'm not familiar with it, you should probably look into their documentation and code a bridge with this repo

**Comment by chrishubert** [comment]
Closing, feel free to re-open if needed
