### ISSUE TITLE
Its possible send message include website link with thumbnail / preview website?

### ISSUE THREAD

**Issue by arislanhaikal** [chrishubert/whatsapp-api#149]
I have some problem for send message include link / website, this message not showing thumbnail / preview website.
Its possible send message with showing thumbnail / preview link?

![IMG_1268](https://github.com/chrishubert/whatsapp-api/assets/14258054/8f879938-651d-46b4-b9c4-00f3d92dc4a1)

In with manual send message, to showing thumbnail we must delay click send button for WA loading thumbnail properly. After thumbnail showing than click send.

Thank you

**Comment by chrishubert** [comment]
In latest version it's enabled by default
https://docs.wwebjs.dev/global.html#MessageSendOptions
