### ISSUE TITLE
Cant Send Message to Group

### ISSUE THREAD

**Issue by rezytijo** [chrishubert/whatsapp-api#153]
**I cant send message to any group, its give me error message**
this my Body Request
```
{
  "chatId": "groupinvite@g.us",
  "contentType": "string",
  "content": "Hello World"
}
```

this is the error message
```
{
    "success": false,
    "error": "Evaluation failed: Error: wid error: invalid wid
   at e (https://web.whatsapp.com/:2:4913)
   at new f (https://web.whatsapp.com/app.4bd18721b02591a90502.js:307:222747)
   at Object.c [as createWid] (https://web.whatsapp.com/app.4bd18721b02591a90502.js:307:229048)
   at __puppeteer_evaluation_script__:2:53"
}
```

i run that Request From Postman

**Comment by chrishubert** [comment]
I tried with the latest version of wwwjs and it works fine, please try again

**Comment by rezytijo** [comment]
Hmm IDK how to solve it, i Already pull latest Docker Image but nothing change for me, i will try to delete my volume and restart from beginning

**Comment by rezytijo** [comment]
Thankyou, now i understand where i can find the Group ID. Thanks

Who ever have same problem with me just run this URL
`http://localhost:3000/client/getChats/{sessionid}`

it will return all your chat and Group with ID
