### ISSUE TITLE
Change this server details

### ISSUE THREAD

**Issue by sunilsankar** [chrishubert/whatsapp-api#155]
Hi is there a way to change the server url from localhost:3000 to some other url 192.168.1.32:3000

![image](https://github.com/chrishubert/whatsapp-api/assets/2275957/85cfa20d-a606-4143-9f5d-eac0fc4bde62)

**Comment by sunilsankar** [comment]
is this possible to change as a variable localhost . Since I am planning to do the deployment in kubernetes
https://github.com/chrishubert/whatsapp-api/blob/master/swagger.json

**Comment by avoylenko** [comment]
Please pull the latest image and retest.

**Comment by sunilsankar** [comment]
It is not working I still see localhost

**Comment by avoylenko** [comment]
@chrishubert could you push a new version to docker hub?

**Comment by chrishubert** [comment]
I was kind of hoping that alpha5 would come out soon for WWebJs.
Anyway, no worries, I pushed a new tag and the image is updated now on Docker Hub
https://github.com/chrishubert/whatsapp-api/releases/tag/v1.23.1-alpha.4-2

**Comment by sunilsankar** [comment]
It works but why cant we remove this completely :) . It will look better
![image](https://github.com/chrishubert/whatsapp-api/assets/2275957/abbf52b8-355d-4da3-85b1-6f9f826b98a5)

**Comment by avoylenko** [comment]
We can't do it, since the swagger specification generated automatically
