### ISSUE TITLE
Some people do not receive messages

### ISSUE THREAD

**Issue by hussein4alaa** [chrishubert/whatsapp-api#157]
Some people do not receive messages and I receive an error message
Will you help me with this problem, please ?
<img width="1324" alt="Screenshot 2024-02-12 at 6 26 31 PM" src="https://github.com/chrishubert/whatsapp-api/assets/13614747/99c009fd-25ef-4626-af06-bca60fd8dd22">

**Comment by chrishubert** [comment]
@hussein4alaa your `wid` is not correct, can you confirm it should be in the format `123456798@c.us`

**Comment by chrishubert** [comment]
Closing as idle
