### ISSUE TITLE
Button chat not showing

### ISSUE THREAD

**Issue by wahyurp** [chrishubert/whatsapp-api#163]
I try to use POST method for '/client/sendMessage/{sessionId}', send body JSON like this.
{
  "chatId": "62811111111@c.us",
  "contentType": "Buttons",
  "viewed": true,
  "content": {
    "body": "Hello World!",
    "buttons": [
      {
        "body": "button 1"
      }
    ],
    "title": "Hello World!",
    "footer": "Hello World!"
  }
}

and the result is
{
    "success": true,
    "message": {
        "_data": {
            "id": {
                "fromMe": true,
                "remote": "62811111111@c.us",
                "id": "3EB0D61163D3235603032E",
                "_serialized": "true_62811111111@c.us_3EB0D61163D3235603032E"
            },
            "viewed": false,
            "body": "Hello World!",
            "type": "chat",
            "t": 1708483593,
            "from": {
                "server": "c.us",
                "user": "62822222222",
                "_serialized": "62822222222@c.us"
            },
            "to": {
                "server": "c.us",
                "user": "62811111111",
                "_serialized": "62811111111@c.us"
            },
            "self": "out",
            "ack": 0,
            "isNewMsg": true,
            "star": false,
            "kicNotified": false,
            "caption": "Hello World!",
            "isFromTemplate": false,
            "title": "Hello World!",
            "pollInvalidated": false,
            "isSentCagPollCreation": false,
            "latestEditMsgKey": null,
            "latestEditSenderTimestampMs": null,
            "mentionedJidList": [],
            "groupMentions": [],
            "footer": "Hello World!",
            "isEventCanceled": false,
            "isVcardOverMmsDocument": false,
            "isForwarded": false,
            "labels": [],
            "hasReaction": false,
            "disappearingModeInitiator": "chat",
            "disappearingModeTrigger": "chat_settings",
            "productHeaderImageRejected": false,
            "lastPlaybackProgress": 0,
            "isDynamicReplyButtonsMsg": true,
            "dynamicReplyButtons": [
                {
                    "buttonId": "1bUVb6",
                    "buttonText": {
                        "displayText": "button 1"
                    },
                    "type": 1
                }
            ],
            "isCarouselCard": false,
            "parentMsgId": null,
            "isMdHistoryMsg": false,
            "stickerSentTs": 0,
            "isAvatar": false,
            "lastUpdateFromServerTs": 0,
            "invokedBotWid": null,
            "bizBotType": null,
            "botResponseTargetId": null,
            "botPluginType": null,
            "botPluginReferenceIndex": null,
            "botPluginSearchProvider": null,
            "botPluginSearchUrl": null,
            "botPluginMaybeParent": false,
            "botReelPluginThumbnailCdnUrl": null,
            "botMsgBodyType": null,
            "requiresDirectConnection": null,
            "links": []
        },
        "id": {
            "fromMe": true,
            "remote": "62811111111@c.us",
            "id": "3EB0D61163D3235603032E",
            "_serialized": "true_62811111111@c.us_3EB0D61163D3235603032E"
        },
        "ack": 0,
        "hasMedia": false,
        "body": "Hello World!",
        "type": "chat",
        "timestamp": 1708483593,
        "from": "62822222222@c.us",
        "to": "62811111111@c.us",
        "deviceType": "android",
        "isForwarded": false,
        "forwardingScore": 0,
        "isStatus": false,
        "isStarred": false,
        "fromMe": true,
        "hasQuotedMsg": false,
        "hasReaction": false,
        "vCards": [],
        "mentionedIds": [],
        "groupMentions": [],
        "isGif": false,
        "title": "Hello World!",
        "links": [],
        "dynamicReplyButtons": [
            {
                "buttonId": "1bUVb6",
                "buttonText": {
                    "displayText": "button 1"
                },
                "type": 1
            }
        ]
    }
}

But it's not showing in 62811111111 chat.

**Comment by avoylenko** [comment]
See https://github.com/chrishubert/whatsapp-api/issues/46
