### ISSUE TITLE
Text Button

### ISSUE THREAD

**Issue by biplob86429** [chrishubert/whatsapp-api#17]
Sir,
Can you please add Text Button with Message ? If possible please do it

**Comment by chrishubert** [comment]
@biplob86429 The buttons have been disabled by WhatsApp, if they are being used – there is a high chance to get your number blocked if you send to Android.
I disabled them in the code until the issue gets fixed.

You can follow up on the original issue there:
https://github.com/pedroslopez/whatsapp-web.js/issues/2093

**Comment by chrishubert** [comment]
@biplob86429 I re-enabled it, remember that it won't work on Android. Use it carefully !
