### ISSUE TITLE
Stops Working on Raspberry Pi

### ISSUE THREAD

**Issue by brunohenriquy** [chrishubert/whatsapp-api#182]
I have been experimenting with running this amazing project on a Raspberry Pi for a few days now, and I've encountered an issue where it ceases to function after a couple of hours of operation. My primary use case involves sporadic message sending throughout the day.

Here's a breakdown of the problem:
- The service initially operates correctly.
- After a few hours, it stops sending messages altogether.
- Upon checking the endpoint `client/getState`, it returns state `CONNECTED`.
- When attempting to send messages using `client/sendMessage`, the operation appears to execute without errors, but the messages are not delivered.
- Upon restarting the container, subsequent calls to `client/getState` return state `null`.

I've also been running the same project on my Mac M1 without encountering any issues. This leads me to suspect that the problem might be related to the Raspberry Pi's architecture. However, I'm uncertain how to proceed with debugging this issue effectively, since no error message is delivered when it "breaks".

To mitigate the problem, I've tried to disable several callbacks to reduce the workload, but it still has the same behavior.

```
DISABLED_CALLBACKS=change_state|group_join|group_leave|group_update|loading_screen|media_uploaded|message|message_ack|message_create|message_reaction|message_revoke_everyone|ready|contact_changed
```

I would greatly appreciate any assistance or insights on how to resolve this issue. Thank you!

**Comment by brunohenriquy** [comment]
**Update:**

Here's the latest update from my recent test:

1. Started fresh by scanning the QR code and initializing it.
2. Checked `client/getState`, and it was functioning properly.
3. Successfully sent a test message using `client/sendMessage`.

Instead of waiting for hours to observe any potential issues, I decided to stop and restart the container. Surprisingly, the service stopped working after this action.

This got me thinking that the problem might be related to how I had my volume mounted. Currently, it's stored on a flash drive connected to a USB port on my Raspberry Pi.

For the next round of testing, I moved the data volume to the main storage. Started all over again. And voila! It worked like a charm! Now, the service survives container reboots and It's been running smoothly for a few hours.

I'll continue monitoring the situation and will provide an update in a few days to confirm if this indeed resolved the issue.

**Comment by avoylenko** [comment]
Might be useful to run the browser in x mode(with ui enabled mode) to see what is hapenning there.

**Comment by brunohenriquy** [comment]
My Raspberry server is headless so this was not an option. =/

**Comment by brunohenriquy** [comment]
That was it, it's running flawlessly!! \o/
