### ISSUE TITLE
Headless 

### ISSUE THREAD

**Issue by eduardohr-muniz** [chrishubert/whatsapp-api#185]
Goodnight. How are you?

Can you give me some advice, on my old machine when I uncommented headless, it opens chromium with WhatsAppweb directly on my windows machine but now I've already installed everything I knew and I can't get it to run, can you give me some light on how to do it this job?

Another thing, can you tell me if it is possible to have a route that shows the WhatsApp screen even with conversations and everything? to put in a webview on my system?

**Comment by avoylenko** [comment]
To be honest, I didn't get what the issue with your deployment. Headless mode should not be disabled in most cases and should be disabled only during troubleshooting sessions.
