### ISSUE TITLE
Cache error when starting the session

### ISSUE THREAD

**Issue by kaua-alves-queiros** [chrishubert/whatsapp-api#192]
when I run the API container, it works perfectly, but when I create the session at /sessions/start/sessionId, it says the session already exists and gives an error when trying to load the session cache.

I've already destroyed the container, deleted the volume, and cleared the contents of /sessions. I've also deleted all project files, cloned it again, and set up everything from scratch, but the problem persists

![image](https://github.com/chrishubert/whatsapp-api/assets/89699012/aa455728-8d94-4a35-9c84-508fa98b62a5)
![image](https://github.com/chrishubert/whatsapp-api/assets/89699012/65e8447d-cb8d-4c26-beb6-a4bb0f63dd56)
![image](https://github.com/chrishubert/whatsapp-api/assets/89699012/3999de88-e1ae-4fe4-a699-a25b1c9fcce2)
![image](https://github.com/chrishubert/whatsapp-api/assets/89699012/0c46c4fe-cef0-4847-a854-643b3572e26e)

**Comment by lucasrodrigues062** [comment]
same happen here with me

**Comment by rolandkulkov** [comment]
i have the same issue

**Comment by lucasrodrigues062** [comment]
> [pedroslopez/whatsapp-web.js#2789](https://github.com/pedroslopez/whatsapp-web.js/issues/2789)

it's works for me. thanks

**Comment by kaua-alves-queiros** [comment]
> [pedroslopez/whatsapp-web.js#2789](https://github.com/pedroslopez/whatsapp-web.js/issues/2789)

I read the issue but couldn't solve it. Could you help me to resolve it? I believe that, since English is not my native language, I might have missed something.

**Comment by rolandkulkov** [comment]
> > [pedroslopez/whatsapp-web.js#2789](https://github.com/pedroslopez/whatsapp-web.js/issues/2789)
> 
> I read the issue but couldn't solve it. Could you help me to resolve it? I believe that, since English is not my native language, I might have missed something.

Change followings to this in .env

`WEB_VERSION=2.3000.1012536975-alpha # OPTIONAL, THE VERSION OF WHATSAPP WEB TO USE
WEB_VERSION_CACHE_TYPE=REMOTE # OPTIONAL, DETERMINTES WHERE TO GET THE WHATSAPP WEB VERSION(local, remote or none), DEFAULT 'none'`

and then use this package in package.json:

`    "whatsapp-web.js": "pedroslopez/whatsapp-web.js#webpack-exodus"
`

before you run npm i make a cleanup ( delete node-modules, and maybe package-lock.json)
With this workaround you will be able to run locally

**Comment by kaua-alves-queiros** [comment]
> > > [pedroslopez/whatsapp-web.js#2789](https://github.com/pedroslopez/whatsapp-web.js/issues/2789)
> > 
> > 
> > I read the issue but couldn't solve it. Could you help me to resolve it? I believe that, since English is not my native language, I might have missed something.
> 
> Change followings to this in .env
> 
> `WEB_VERSION=2.3000.1012536975-alpha # OPTIONAL, THE VERSION OF WHATSAPP WEB TO USE` `WEB_VERSION_CACHE_TYPE=REMOTE # OPTIONAL, DETERMINTES WHERE TO GET THE WHATSAPP WEB VERSION(local, remote or none), DEFAULT 'none'`
> 
> and then use this package in package.json:
> 
> ` "whatsapp-web.js": "pedroslopez/whatsapp-web.js#webpack-exodus"`
> 
> before you run npm i make a cleanup ( delete node-modules, and maybe package-lock.json) With this workaround you will be able to run locally

It wasn't working for me, but after I tried running it directly on my PC instead of trying to run it through Docker, it worked. I checked and the compose file doesn't use the .env file; it has the variables defined inside it. So, for anyone using it via Docker, they should make the exact same change, but in the docker-compose.yaml file. Thank you very much for your help!
