### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by dr400** [chrishubert/whatsapp-api#195]
Hi (new version installed, the one you uploaded 3h ago), docker-compose is v2.26.1, docker is 20.10.23 on synology (no way to update it, at least easily)

"Failed to send new message webhook: ABCD qr Request failed with status code 404 {" 

followed by "qr: '.....'"

**Comment by avoylenko** [comment]
Check your webhook url for that whatsapp instance

**Comment by dr400** [comment]
> Check your webhook url for that whatsapp instance

Oh thanks for your reply. But how to do that ? (noob here ...)

**Comment by avoylenko** [comment]
> > Check your webhook url for that whatsapp instance
> 
> Oh thanks for your reply. But how to do that ? (noob here ...)

https://github.com/chrishubert/whatsapp-api/blob/43ca3183664dce8911d21520ce68f835a85e83f2/README.md?plain=1#L145

**Comment by dr400** [comment]
> > > Check your webhook url for that whatsapp instance
> > 
> > 
> > Oh thanks for your reply. But how to do that ? (noob here ...)
> 
> https://github.com/chrishubert/whatsapp-api/blob/43ca3183664dce8911d21520ce68f835a85e83f2/README.md?plain=1#L145

mine is set to : - BASE_WEBHOOK_URL=http://192.168.xxx.xxx:3000
