### ISSUE TITLE
Session Success but close again

### ISSUE THREAD

**Issue by mdestafadilah** [chrishubert/whatsapp-api#203]
Session succesfully paired, few seconds has been disconnected. after update the latest.

**Comment by mdestafadilah** [comment]
> Same here. Anyone has a solution?

No, it's issue about ```whatsapp-web.js```

follow this issue https://github.com/chrishubert/whatsapp-api/issues/189#issue-2222685118

not working.

**Comment by arislanhaikal** [comment]
I have some issue,
I use latest docker compose
after connected and i check session result

`{
  "success": false,
  "state": null,
  "message": "browser tab closed"
}`

any solution?

**Comment by mdestafadilah** [comment]
> I have some issue, I use latest docker compose after connected and i check session result
> 
> `{ "success": false, "state": null, "message": "browser tab closed" }`
> 
> any solution?

follow this https://github.com/chrishubert/whatsapp-api/issues/189#issuecomment-2089405230
