### ISSUE TITLE
Integration with WhiskeySockets/Baileys (question)

### ISSUE THREAD

**Issue by Wil-Rs** [chrishubert/whatsapp-api#205]
Is there a branch that uses WhiskeySockets/Baileys?
If anyone can help me I would be grateful

**Comment by chrishubert** [comment]
Hello, we are not yet supporting other libraries beside wwjs

**Comment by kslakhani** [comment]
> Hello, we are not yet supporting other libraries beside wwjs

It would be great if you could :)
