### ISSUE TITLE
break line whatsapp character

### ISSUE THREAD

**Issue by fadelmi12** [chrishubert/whatsapp-api#209]
hi, i manage to send message to WhatsApp group, but the break line character "%0a" that i usually use in the other library doesn't work on this library, do you have any solutions ? thanks

**Comment by rodrigoamds** [comment]
To add a line break in a WhatsApp message using the library you mentioned, you should use the newline character \n instead of %0A or %0a.

**Comment by chrishubert** [comment]
Closing as explained
