### ISSUE TITLE
could you implement a method to restart the session when its recovery does not go as planned

### ISSUE THREAD

**Issue by DenysSamoiliuk** [chrishubert/whatsapp-api#214]
from time to time such situations occur when you change the markup and restart the container, or take out other nuances when the session stops responding and you restart the session, it is not restored the first time, sometimes it takes up to 6 restarts, but in the documentation, I saw the method and it seems to solve the problem after restarting the session

https://docs.wwebjs.dev/Client.html#resetState

**Comment by chrishubert** [comment]
Not sure if it helps, but we can indeed add `resetState` to the library
