### ISSUE TITLE
Ubuntu Docker or Local version

### ISSUE THREAD

**Issue by jaycoper** [chrishubert/whatsapp-api#216]
Anyone got it working on a Ubuntu as Docker or Local version?

**Comment by chrishubert** [comment]
It is working in Docker well, could you please provide more info?

**Comment by jaycoper** [comment]
Hi Chris, thank for everything.
I cleaned up the Ubuntu server and re-installed everything, and updated

It started off with some error messages about pptr://__puppeteer_evaluation_script__:2:26

whatsapp_web_api | Failed to send new message webhook: OWN1 ready Request failed with status code 404
whatsapp_web_api | Failed to send new message webhook: OWN1 group_update Request failed with status code 404 {


I used ENABLE_LOCAL_CALLBACK_EXAMPLE=TRUE 
Now I can at least connect and stay connected and send message, thanks.
