### ISSUE TITLE
Memory Leakage?

### ISSUE THREAD

**Issue by Ant0nioSouza** [chrishubert/whatsapp-api#218]
When I run the project using `npm run start`, the memory usage is fine. However, after a few hours, the memory consumption increases to 50% and continues to rise. I have observed it reaching 97%.
What can I do to reduce this effect?

**Comment by TommyLeong** [comment]
I have noticed the same on my end, the memory usage consumption kept increasing until the limit and application is reach EOL. It takes only about 5 days to kill my server which running on a 8GB ram. 

<img width="440" alt="image" src="https://github.com/chrishubert/whatsapp-api/assets/9990179/ec348b35-17cc-468c-8f99-3b505ef3aaff">

@Ant0nioSouza  did you manage to overcome this issue in anyway?
Meantime, @chrishubert would be great if we could get your 2 cents. 🙏🏻

**Comment by Ant0nioSouza** [comment]
> I have noticed the same on my end, the memory usage consumption kept increasing until the limit and application is reach EOL. It takes only about 5 days to kill my server which running on a 8GB ram.
> 
> <img alt="image" width="440" src="https://private-user-images.githubusercontent.com/9990179/345873138-ec348b35-17cc-468c-8f99-3b505ef3aaff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4Nzc5NDUsIm5iZiI6MTcyMDg3NzY0NSwicGF0aCI6Ii85OTkwMTc5LzM0NTg3MzEzOC1lYzM0OGIzNS0xN2NjLTQ2OGMtOGY5OS0zYjUwNWVmM2FhZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTNUMTMzNDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjllOTUyNWZmYmNmMjY0YWY3NmM5ZjBiNjIzYWM2MGYxZGE4N2YzY2UyNWE5ZGQ0ZjAxZjNjMzIyMjYyYWIyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zByyUp9YFWGtdFxrQ7nA13RkkmZcxj4KqLI3hNAETGs">
> @Ant0nioSouza did you manage to overcome this issue in anyway? Meantime, @chrishubert would be great if we could get your 2 cents. 🙏🏻

Sorry for late response...
I don't know exactly what the problem is, but after I deleted the sessions folder I no longer had this problem.

**Comment by mdestafadilah** [comment]
> I have noticed the same on my end, the memory usage consumption kept increasing until the limit and application is reach EOL. It takes only about 5 days to kill my server which running on a 8GB ram.
> 
> <img alt="image" width="440" src="https://private-user-images.githubusercontent.com/9990179/345873138-ec348b35-17cc-468c-8f99-3b505ef3aaff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjI4NjYsIm5iZiI6MTcyMTk2MjU2NiwicGF0aCI6Ii85OTkwMTc5LzM0NTg3MzEzOC1lYzM0OGIzNS0xN2NjLTQ2OGMtOGY5OS0zYjUwNWVmM2FhZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjZUMDI1NjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjg5ZTNjOWVhMzliOWY1NjgxNDY4NWQwMGRmNzY3YmE5ZjgxZDA1N2EyYmZkNmRiZDc4YWU3NzIxODIxYTZhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XVRKlqQwn2Bvzt47i9Vh9snrFGLvmKXNyvVqDzAYA8w">
> @Ant0nioSouza did you manage to overcome this issue in anyway? Meantime, @chrishubert would be great if we could get your 2 cents. 🙏🏻

still exist? try update your chrome, cz this REST api using wweb-js exactly using chromium...

**Comment by HambaBersalah** [comment]
yep the same, how can this ws api use db instead of memory? you help would be really helpful, thank you

**Comment by mdestafadilah** [comment]
> yep the same, how can this ws api use db instead of memory? you help would be really helpful, thank you

try running with PM2, if resource is hight, will be restart autmaticaly, i have 4 service with different library, like venom, baileys, and wweb.js my server running well.

<img width="608" alt="14-11-2024 09-13-07" src="https://github.com/user-attachments/assets/15fc311d-6e75-4f57-8062-49ac14befc21">

here i'm monitoring my service

![screencapture-uptime-persahabatan-co-id-status-wa-2024-11-14-09_14_24](https://github.com/user-attachments/assets/1ed91419-11fb-42d2-810c-e8429c218e60)

**Comment by HambaBersalah** [comment]
> > yep the same, how can this ws api use db instead of memory? you help would be really helpful, thank you
> 
> try running with PM2, if resource is hight, will be restart autmaticaly, i have 4 service with different library, like venom, baileys, and wweb.js my server running well.
> 
> <img alt="14-11-2024 09-13-07" width="608" src="https://private-user-images.githubusercontent.com/5575882/386015610-15fc311d-6e75-4f57-8062-49ac14befc21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2ODY4NDAsIm5iZiI6MTczMTY4NjU0MCwicGF0aCI6Ii81NTc1ODgyLzM4NjAxNTYxMC0xNWZjMzExZC02ZTc1LTRmNTctODA2Mi00OWFjMTRiZWZjMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMTYwMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjNiZDk2MWVhYzhlYmZmZjNjZTk0MjA0ZjQ2MWNjZGQ2MTQ2MzBhNzc0MmMwNWY0OTBiMzcxMjNmODZjNGM1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.MVADKyLJZOLSJHOU3lSZc0FmqPScnaI75yIgoq0NFds">
> here i'm monitoring my service
> 
> ![screencapture-uptime-persahabatan-co-id-status-wa-2024-11-14-09_14_24](https://private-user-images.githubusercontent.com/5575882/386015863-1ed91419-11fb-42d2-810c-e8429c218e60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2ODY4NDAsIm5iZiI6MTczMTY4NjU0MCwicGF0aCI6Ii81NTc1ODgyLzM4NjAxNTg2My0xZWQ5MTQxOS0xMWZiLTQyZDItODEwYy1lODQyOWMyMThlNjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMTYwMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmJjMTI4NTg0NTcxMWFiMzAyMDk0ZWQ3MzA0OGM1MThiZGRmMDliMzZiYmE1NjNlMWQzMWIwMmQxN2Q3MTE1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.u09hiZpf3WJIa1DDnDP5R_fMIA_BmdYFGs8anEkJoLQ)

Thank you @mdestafadilah , i will try it, this information is really helpful, thank you for helping me out

**Comment by Ant0nioSouza** [comment]
I'm closing this issue!
If someone has the same problem take a look at the @mdestafadilah response and check if you don't have multiple session opened.
