### ISSUE TITLE
Send image with caption

### ISSUE THREAD

**Issue by flourigh** [chrishubert/whatsapp-api#257]
how send message with caption?

**Comment by flourigh** [comment]
use this
`
          chatId: "55999999999@c.us',
          contentType: "string",
          content: "text caption",
          options: {
            media: {
              "mimetype": "image/jpeg",
              data: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
            }
          },
        `

**Comment by flourigh** [comment]
use this
`
          chatId: "55999999999@c.us',
          contentType: "string",
          content: "text caption",
          options: {
            media: {
              "mimetype": "image/jpeg",
              data: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
            }
          },
        `

**Comment by KushX** [comment]
> use this
> 
> ```
>           chatId: "55999999999@c.us',
>           contentType: "string",
>           content: "text caption",
>           options: {
>             media: {
>               "mimetype": "image/jpeg",
>               data: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
>             }
>           },
> ```

Hello!
I've attempted the same but with .mimetype = "application/pdf".
File works well, however it seems the .filename no longer works and shows up as "null".
Any fix for this?

**Comment by neucrk** [comment]
Send the document as "MessageMedia", this way:

chatId: "55999999999@c.us',
contentType: "MessageMedia",
content: {
    "mimetype": "image/jpeg",
    "data": "iVBORw0KGgoAAAANSUhE...k+A8AAQUBAScY42YAAAAASUVORK5CYII=",
    "filename": "Document-12345.pdf"
}

**Comment by KushX** [comment]
> Send the document as "MessageMedia", this way:
> 
> chatId: "[55999999999@c.us](mailto:55999999999@c.us)', contentType: "MessageMedia", content: { "mimetype": "application/pdf", "data": "iVBORw0KGgoAAAANSUhE...k+A8AAQUBAScY42YAAAAASUVORK5CYII=", "filename": "Document-12345.pdf" }

On your suggestion, you can't add a text along with the message.
And vice versa, if you send a text with the pdf, then you cannot name the file (shows up as "null".
<a href="https://i.imgur.com/1EjRwi4.png">https://i.imgur.com/1EjRwi4.png</a>
