### ISSUE TITLE
Idle session auto-termination

### ISSUE THREAD

**Issue by biplob86429** [chrishubert/whatsapp-api#27]
Sir,
When i create an Instance it continue send QR code in call back in every second . it stop when Instance is Deleted.

My point is:
After creating an instance , After 1-2  minute , if QR not scan within 2 minute , this will go to sleep mode and will not send any Call back for that QR of specific Instance.

Later if need to Scan QR again , we have to call a api and then again QR receving will start.

It may help us to Reduce server Load

**Comment by chrishubert** [comment]
That should be doable, let me look into it
