### ISSUE TITLE
error Couldn't find match for "webpack-exodus" in

### ISSUE THREAD

**Issue by yughoz** [chrishubert/whatsapp-api#276]

**Comment by theeusmartins** [comment]
here with the same error

**Comment by mdestafadilah** [comment]
no update here???

**Comment by avoylenko** [comment]
You can manually bump the whatsapp-web.js dependency

**Comment by mdestafadilah** [comment]
> You can manually bump the whatsapp-web.js dependency

why not pointing to mayor version?

**Comment by avoylenko** [comment]
@mdestafadilah feel free to open PR

**Comment by avoylenko** [comment]
Project dependencies have been updated

**Comment by yughoz** [comment]
oke thanks
