### ISSUE TITLE
Bug: window.Store.ProfilePic.profilePicFind is not a function on all routes for receiving image URLs

### ISSUE THREAD

**Issue by tomy1989** [chrishubert/whatsapp-api#282]
This issue occurs on all routes where I expect to receive the image URL for the user's profile picture.
Using chrishubert/whatsapp-web-api:v1.23.1-webpack-exodus.1

## Suggested Solution
I found a possible solution where the function name might have been changed to `window.Store.ProfilePic.requestProfilePicFromServer`. It seems like this function may now handle fetching profile pictures from the server, and updating the code accordingly might resolve the issue.

**Comment by avoylenko** [comment]
Pull the latest docker image. Should be already fixed there.
