### ISSUE TITLE
Issue: Chromium Profile Lock Error During Initialization

### ISSUE THREAD

**Issue by tomy1989** [chrishubert/whatsapp-api#283]
I encountered an issue where Chromium profiles are being locked by another process, causing the following error when attempting to initialize new sessions:
Initialize error: Failed to launch the browser process!
[37:37:1021/124411.842146:ERROR:process_singleton_posix.cc(358)] The profile appears to be in use by another Chromium process (36) on another computer (e77b1ebe9b51). Chromium has locked the profile so that it doesn't get corrupted. If you are sure no other processes are using this profile, you can unlock the profile and relaunch Chromium.

**Comment by Azathoth88** [comment]
@tomy1989 I have the same problem. How do you solve this?

**Comment by Azathoth88** [comment]
@tomy1989 Thank you very much for your detailed answer and your help! It has helped me!

**Comment by avoylenko** [comment]
We could implement the logic of removing the lock file on session start, but i don't know how painful the issue is to do so.

**Comment by Azathoth88** [comment]
How about an optional ENV?

**Comment by vsnshanmuganathan** [comment]
> It has helped me!

I get permission denied, could anyone help me out there?

**Comment by avoylenko** [comment]
@Azathoth88 @tomy1989 I have forked the project and implemented the logic there https://github.com/avoylenko/wwebjs-api

The SingletonLock file will be removed automatically and won't stop the instance from running.
