### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by andrelmariano** [chrishubert/whatsapp-api#29]
hello, I did not find these things in the documentation, can you tell? everything I tried didn't work either, can you help with easas 3 questions?

How can I send a message to a number?

How can I send a message to a group?

how can i create a group?

**Comment by chrishubert** [comment]
https://editor.swagger.io/?url=https://raw.githubusercontent.com/chrishubert/whatsapp-api/master/swagger.json
1. Doc is a tad lacking for send message, `/client/sendMessage/{sessionId}`
2. Create Group should be straightforward `/client/createGroup/{sessionId}`

**Comment by lascimmia** [comment]
> How can I send a message to a number?

I'll try to give a response to this question. Try this, it should work:

`curl -X 'POST' 'http://loclahost:3000/client/sendMessage/<SESSION NUMBER>' -H 'accept: */*' -H 'Content-Type: application/json' -d '{"chatId": "<RECEIVER NUMBER>@c.us", "contentType": "string", "content": "<PUT YOUR MESSAGE HERE>"}'`

Beside I'm not able to send a image with the command:

`curl -X 'POST' 'http://localhost:3000/client/sendMessage/<SESSION NUMBER>' -H 'accept: */*' -H 'Content-Type: application/json' -d '{"chatId": "<RECEIVER NUMBER>@c.us", "contentType": "MessageMediaFromURL", "content": "<IMAGE URL>", "caption": "<CAPTION>", "filename": "<FILENAME>"}'`

In particular, it does not change the caption and the filename. While the file is an image produced by a PHP script online, it does call the file <SOMETHING>.php, no preview and the caption remains <SOMETHING>.php

**Comment by chrishubert** [comment]
@lascimmia I actually always send the image manually in base64 and enforcing the MIME type.
I would assume the `qrcode.php` is not returning the proper MIME type and therefore is showing as a php file.
Do you have a URL I can try?

For the documentation, send message is indeed quite bad, I'll get a burst of motivation this week and update it

**Comment by chrishubert** [comment]
Now, this is from the original library – Their mime type handling is a bit wrong.

https://github.com/pedroslopez/whatsapp-web.js/blob/d8fd4579143624384004c1f966bb1d92f0a69036/src/structures/MessageMedia.js#L72

Basically, they "read" the path first to look for the extension (in your case `.php`)
So it should now work if you don't use a `.php` extension, but will work otherwise (I added the `unsafeMime` by default in the last release)

**Comment by chrishubert** [comment]
CLosing as done
![image](https://github.com/chrishubert/whatsapp-api/assets/8528436/a610069e-687f-4d93-8660-eea05d36c1d1)
