### ISSUE TITLE
 It's is possible to get user is online or offline status by contact id ?

### ISSUE THREAD

**Issue by fenilinvica** [chrishubert/whatsapp-api#31]
it's work ?

**Comment by chrishubert** [comment]
I'm not sure if I understand the question properly. Mayeb this will answer:
This API behaves the same way as https://web.whatsapp.com/ 
So if the number works in Whatsapp Web, it will work in this API.

**Comment by fenilinvica** [comment]
sorry for lat my question is how to get a user status if it's online or offline status if any way to doing this scrap

**Comment by chrishubert** [comment]
This information is only available in the mobile application, and not in [WhatsApp](https://web.whatsapp.com/), you will not be able to retrieve it through this API at this time.

Some implementation have been tried but failed 😢
https://github.com/pedroslopez/whatsapp-web.js/issues/82

**Comment by fenilinvica** [comment]
**https://play.google.com/store/apps/details?id=com.welog**
 see this demo apk doing same thing how ? any idea give me a hint so i can do it

**Comment by chrishubert** [comment]
@fenilinvica, the one you showed is working on mobile device.
You will not be able to use this repo, which works as a desktop Chrome browser emulator that opens https://web.whatsapp.com/

**Comment by fenilinvica** [comment]
ok
