### ISSUE TITLE
Bulk Message

### ISSUE THREAD

**Issue by mdestafadilah** [chrishubert/whatsapp-api#36]
Can this API supply bulk message with delay by default?

**Comment by chrishubert** [comment]
@mdestafadilah, this is not in the roadmap - I would recommend making this logic directly on your back-end side

**Comment by mdestafadilah** [comment]
> @mdestafadilah, this is not in the roadmap - I would recommend making this logic directly on your back-end side

ya, i know, i have do it. no problem if it's not roadmap. btw thanks for your cool whatsapp api.
