### ISSUE TITLE
Https is not Working

### ISSUE THREAD

**Issue by mdestafadilah** [chrishubert/whatsapp-api#37]
I'm trying develop with HTTPS but it's failed, *forbiden status* when i change to http, it's normal.

i'm trying running production mode with nodejs command 

```bash
node server.js
```

**Comment by chrishubert** [comment]
@mdestafadilah, you should run it behind a reverse proxy like `nginx` to handle the https part

**Comment by mdestafadilah** [comment]
it's done. i'm running different path of node js version, thanks btw for this API.
