### ISSUE TITLE
/client/archiveChat/{session}

### ISSUE THREAD

**Issue by lascimmia** [chrishubert/whatsapp-api#39]
I cannot figure out how to archive a chat.
I tryed to read whatsapp-web.js documentation with no success.
Can you help me?

**Comment by chrishubert** [comment]
@lascimmia I haven't used that function actually – let me give it a try this weekend

**Comment by lascimmia** [comment]
You are really kind!

**Comment by chrishubert** [comment]
![image](https://github.com/chrishubert/whatsapp-api/assets/8528436/33ef7a32-dd11-43eb-afa0-0375f52cb5a1)
I managed to archive the chat without issue, please follow the format above.

**Comment by chrishubert** [comment]
I will close this issue for now - feel free to open it again if there is new details

**Comment by lascimmia** [comment]
Sure, thank you!

Il mer 28 giu 2023, 08:14 Christophe ***@***.***> ha scritto:
