### ISSUE TITLE
QRCODE

### ISSUE THREAD

**Issue by ezequieltomazini** [chrishubert/whatsapp-api#57]
hello!

I was able to install it, but I am not able to show the QRCODE in a URL so that it can be scanned, how could I do that?

thanks.

**Comment by avoylenko** [comment]
@ezequieltomazini if you have the environment variable set as `BASE_WEBHOOK_URL=http://localhost:3000/localCallbackExample` and `ENABLE_LOCAL_CALLBACK_EXAMPLE=TRUE ` the QR code will be printed to your terminal window.

**Comment by ezequieltomazini** [comment]
Thanks for the feedback.
Can you return the QR code, but it does not come in a BASE64 image, what format is it?

Thank you very much.

**Comment by avoylenko** [comment]
I didn't get what are you trying to achieve.  If you need BASE64 string you need the qrcode package. The [whatsapp-api](https://github.com/chrishubert/whatsapp-api) service is able to render only picture to the terminal window

```
var QRCode = require('qrcode')

QRCode.toDataURL(qrData, function (err, url) {
  console.log(url)
})
```

**Comment by chrishubert** [comment]
@ezequieltomazini we return the **content** of the QR code, **not the image** of the QR Code
It is up to you to generate the QR Code of the content yourself.
An example of QR Code generator can be found there: https://www.nayuki.io/page/qr-code-generator-library

**Comment by chrishubert** [comment]
I close that one for the time being, feel free to reopen if not clear
