### ISSUE TITLE
Unexpected message is delivered

### ISSUE THREAD

**Issue by owen2345** [chrishubert/whatsapp-api#65]
Hi,

In my logs I see that the following message is delivered every time I start a new session, what is that?
```
Failed to send new message webhook: ABCD media Request failed with status code 413 {
  messageMedia: MessageMedia {
    mimetype: 'video/mp4',
    data: 'AAAAHGZ0eXBtcD.....'
message: Message {
    _data: {
      id: [Object],
      body: '',
      type: 'video',
      t: 1690598727,
      notifyName: '',
      from: 'status@broadcast',
      to: '59179716902@c.us',
      author: '59160785276@c.us',
```
After decoding the above message, I see this:
<img width="636" alt="image" src="https://github.com/chrishubert/whatsapp-api/assets/1148415/3e8c59d8-38d5-46ae-9434-87513a7855ab">

Thanks,

**Comment by avoylenko** [comment]
Whatsapp team might changed something on whatsapp web page. Let's track here:

https://github.com/pedroslopez/whatsapp-web.js/issues/2346

**Comment by owen2345** [comment]
I see, thanks for your quick anwers

**Comment by avoylenko** [comment]
@owen2345 for now it would ignore messages that are coming from  'status@broadcast'

**Comment by chrishubert** [comment]
@owen2345, we will close the issue for the time being – feel free to re-open if you need more details
