### ISSUE TITLE
WhatsApp messages not sending

### ISSUE THREAD

**Issue by jappads** [chrishubert/whatsapp-api#68]
Is anyone experiencing an issue with whatsapp messages stop sending about 2 days ago. IT was working fine all along and then 2 days ago messages keep failing. Any ideas?

**Comment by avoylenko** [comment]
@jappads have you tried the latest image?

**Comment by jappads** [comment]
Yes, I am running the latest image that was published 5 days ago.

Thanks for your quick response.

If I could confirm that it's working on another end then it would help me
to isolate the issue. If it's with my setup or it's a code wide issue

**Comment by avoylenko** [comment]
We had an issue as well, that's why we updated the **whatsapp-web.js** library and pushed the newest version yesterday to the docker hub.

**Comment by jappads** [comment]
Ok, thanks for the update. I did not see that update. I will check it out
and let you know. Also let me know of anyway I can contribute to
this project

**Comment by jappads** [comment]
I used git pull to get latest code but it still didnt work. Do i have to install docker going forward? I dont have docker installed

**Comment by avoylenko** [comment]
Didn't you forget to run `npm install` after git pull?

**Comment by jappads** [comment]
I have to run npm install after each git pull?

**Comment by jappads** [comment]
Issue was with node.js installation. Once that was fixed, problem was solved
