### ISSUE TITLE
Puppeteer Evaluation Failed

### ISSUE THREAD

**Issue by arktnld** [chrishubert/whatsapp-api#71]
I encountered the following error when trying to send a message:

```json
{"success": false, "error": "Evaluation failed: TypeError: Cannot read properties of undefined (reading 'createWid')\n at __puppeteer_evaluation_script__:2:53"}

**Comment by avoylenko** [comment]
I would try to set  the `WEB_VERSION` variable, it seems like the current one is not working in your case.  The list of all possible whatsapp versions can be found [here](https://github.com/wppconnect-team/wa-version/tree/main/html)

**Comment by arktnld** [comment]
The problem was because I saved the instance and tried to run it recovering the backup  and that somehow broke the api, running the conventional way with docker-compose solves the problem.
