### ISSUE TITLE
QRCode auth in Web

### ISSUE THREAD

**Issue by victorhdchagas** [chrishubert/whatsapp-api#72]
Hi, i would like to suggest to implement qrcode visibility in web browser (when accessing session start endpoint).
This project apparently works well on CasaOS Home assistance, all based in docker compose applications.
This way, i cant see qrcode on docker startup.

**Comment by chrishubert** [comment]
Hello, this would deviate the way the original repository has been designed (event based)
You have to wait for the QR event and handle it on your side. I know this is not very convenient in your case, where I assume you just want to send messages.

If the original repository is proposing this new logic, then we will implement it as well in this repo.
