### ISSUE TITLE
convert qr_code from webhook

### ISSUE THREAD

**Issue by renatoiub** [chrishubert/whatsapp-api#77]
How do I convert the qr_code that comes in the webhook to a qr_code in a format that I can scan on the device?

**Comment by chrishubert** [comment]
Hi @renatoiub it will depend on your backend – what language you are using. 
There are many libraries available for generating QR code from string.
You can also use API for that if you need: ie https://api.qrserver.com/v1/create-qr-code/?data=your_qr_code_data

**Comment by chrishubert** [comment]
I'll close for the time being, feel free to re-open as needed
