### ISSUE TITLE
Versionning

### ISSUE THREAD

**Issue by owen2345** [chrishubert/whatsapp-api#78]
Thanks for the great repo!!!
I'd suggest two things:
- create git tags for every release? So, we that we can compare changes between versions
- create tags for docker images, so that we can use old image versions as sometimes the lastest one could fail
<img width="447" alt="image" src="https://github.com/chrishubert/whatsapp-api/assets/1148415/993551d8-0253-4ef5-89a6-0245c83c6919">

**Comment by chrishubert** [comment]
closing as duplicate
