### ISSUE TITLE
Can no longer send messages

### ISSUE THREAD

**Issue by owen2345** [chrishubert/whatsapp-api#79]
After I updated to the latest docker image, I can no longer send messages. I always receive `{"success":false,"error":"session_not_connected"}` even I restarted the session many times for different devices

**Comment by avoylenko** [comment]
new version just released and available on docker hub

**Comment by chrishubert** [comment]
I'll play with the CI/CD soon to set the versioning, following the wwjs versions

**Comment by owen2345** [comment]
The new release does not include the hotfix: 
```
"whatsapp-web.js": "https://github.com/Julzk/whatsapp-web.js/tarball/jkr_hotfix_8"
```

**Comment by avoylenko** [comment]
@owen2345 it not true, check this out https://github.com/pedroslopez/whatsapp-web.js/issues/2433

**Comment by chrishubert** [comment]
@owen2345 , in the spirit of this repository, we will deploy only the official releases from wwjs
I agree with the versioning to ensure that users get a chance to rollback in case of issues, but for the time being we will not include hotfixes in the repo directly

**Comment by mdestafadilah** [comment]
@chrishubert so we still waiting from repo official wwjs? still not send messages.

**Comment by avoylenko** [comment]
@mdestafadilah do you run the latest docker image?

**Comment by mdestafadilah** [comment]
> @mdestafadilah do you run the latest docker image?

i'm not using docker btw

**Comment by avoylenko** [comment]
@mdestafadilah run `git pull` and `npm i` in the project folder and let me know if that helped.

**Comment by mdestafadilah** [comment]
> @mdestafadilah run `git pull` and `npm i` in the project folder and let me know if that helped.

not work. still same, can't send message

**Comment by mdestafadilah** [comment]
Hi @avoylenko it's relate this case ?
https://github.com/chrishubert/whatsapp-api/issues/82#issuecomment-1709680044

**Comment by owen2345** [comment]
In my case I had to create another image: https://github.com/owen2345/whatsapp
And use this temporary fix: https://github.com/owen2345/whatsapp/blob/main/package.json#L5
```js
"whatsapp-web.js": "https://github.com/Julzk/whatsapp-web.js/tarball/jkr_hotfix_8"
```

**Comment by mdestafadilah** [comment]
> In my case I had to create another image: https://github.com/owen2345/whatsapp And use this temporary fix: https://github.com/owen2345/whatsapp/blob/main/package.json#L5
> 
> ```js
> "whatsapp-web.js": "https://github.com/Julzk/whatsapp-web.js/tarball/jkr_hotfix_8"
> ```

it's resolved?

**Comment by owen2345** [comment]
Yes, it is working

**Comment by mdestafadilah** [comment]
> Yes, it is working

Thanks it's working too, so i'm using your trick. if wwjs launch offically, may @chrishubert will update this repo.

**Comment by chrishubert** [comment]
@owen2345 I used the same dependency as your repo for the time being, until there is an official fix from wwebjs

**Comment by deepakvshinde** [comment]
I am also facing the same issue of not being able to send messages. but the session is active consistently if we restart the server then it works fine but the server is stuck after some time again. (using Ubuntu server). can anyone have an idea on this?

**Comment by yoyococo700** [comment]
Same issue here

> I am also facing the same issue of not being able to send messages. but the session is active consistently if we restart the server then it works fine but the server is stuck after some time again. (using Ubuntu server). can anyone have an idea on this?

**Comment by avoylenko** [comment]
@deepakvshinde  @yoyococo700 could you try the latest build?

**Comment by yoyococo700** [comment]
I just tried the v1.22.2-alpha.1 it seems to work perfectly! Thanks!

**Comment by mahmoudgoogle** [comment]
I have the same problem when sending a message
      
```
{
  "success": false,
  "error": "contentType invalid, must be string, MessageMedia, MessageMediaFromURL, Location, Buttons, or List"
}
```
I use docker

**Comment by avoylenko** [comment]
@mdestafadilah the error message is self-explanatory. Double-check that you send a valid request.

**Comment by mahmoudgoogle** [comment]
> @mdestafadilah the error message is self-explanatory. Double-check that you send a valid request.

I checked everything
Request body
```
{
   "chatId": "201100000@c.us",
   "contentType": "string",
   "content": "Hello World"
}
```

**Comment by avoylenko** [comment]
Do you have `Content-Type: application/json` header in your request?

**Comment by mahmoudgoogle** [comment]
> Do you have `Content-Type: application/json` header in your request?
I forgot to add Content-Type
It's working now. Thank you.
