### ISSUE TITLE
Using Webhook

### ISSUE THREAD

**Issue by mdestafadilah** [chrishubert/whatsapp-api#81]
Hi Chris, 

how we use other webhook.site alternative like

`https://github.com/syifarahmat/webhook`

what can i do? after.

**Comment by avoylenko** [comment]
@mdestafadilah are you trying to run multiply whatsapp instances and need a unique webhook for each instance?

**Comment by mdestafadilah** [comment]
> @mdestafadilah are you trying to run multiply whatsapp instances and need a unique webhook for each instance?

yes.

**Comment by avoylenko** [comment]
@mdestafadilah it's mention in the project README:

> By default, all callback events are delivered to the webhook defined with the BASE_WEBHOOK_URL environment variable. This can be overridden by setting the *_WEBHOOK_URL environment variable, where * is your sessionId. For example, if you have the sessionId defined as DEMO, the environment variable must be DEMO_WEBHOOK_URL

**Comment by mdestafadilah** [comment]
> @mdestafadilah it's mention in the project README:
> 
> > By default, all callback events are delivered to the webhook defined with the BASE_WEBHOOK_URL environment variable. This can be overridden by setting the *_WEBHOOK_URL environment variable, where * is your sessionId. For example, if you have the sessionId defined as DEMO, the environment variable must be DEMO_WEBHOOK_URL

sorry, my mistake read this intruction, thanks bro.
