### ISSUE TITLE
Always get session_not_connected

### ISSUE THREAD

**Issue by isenganim** [chrishubert/whatsapp-api#82]
Hello,

I don't know why after success scan barcode then wait until some minutes then try to call `session/status/:sessionId` always get response below.

![image](https://github.com/chrishubert/whatsapp-api/assets/75124761/159409fe-6bab-43cb-9edd-a5d61a7e1c64)

Running with docker.

Could you help me?

Thanks.

**Comment by isenganim** [comment]
solved with update Client.js 

https://github.com/pedroslopez/whatsapp-web.js/issues/2473#issuecomment-1707469920

**Comment by mdestafadilah** [comment]
> solved with update Client.js
> 
> [pedroslopez/whatsapp-web.js#2473 (comment)](https://github.com/pedroslopez/whatsapp-web.js/issues/2473#issuecomment-1707469920)

I think chris will not do, cz he try to clean a code from wwjs.

**Comment by chrishubert** [comment]
@mdestafadilah @isenganim I pushed the hotfix already 🙏
