### ISSUE TITLE
how to add qr code by image in {{baseUrl}}/session/start/:sessionid

### ISSUE THREAD

**Issue by Adityasundawa** [chrishubert/whatsapp-api#84]
I need images to be displayed on my frontend

**Comment by deepakvshinde** [comment]
For this requirement, i have modified two functions when we create a session at that time In response I'm passing qrcode in return response. modified functions 
1. startSession

const startSession = async (req, res) => {
  try {
    const sessionId = req.params.sessionId
    const { qrCodePromise } = await setupSession(sessionId) // Get the client and QR code promise
    const qrCode = await qrCodePromise
    res.json({ success: true, message: 'QR Code generated', qrCode })
  } catch (error) {
    sendErrorResponse(res, 500, error.message)
  }
}

2. setupSession 
const setupSession = async (sessionId) => {
  try {
  // keep existing code as it is 
    const client = new Client(clientOptions)
    client.initialize().catch(err => console.log('Initialize error:', err.message))
    const qrCodePromise = initializeEvents(client, sessionId) // Get the QR code promise
    sessions.set(sessionId, client)
    return { success: true, message: 'Session initiated successfully', qrCodePromise }
  } catch (error) {
    return { success: false, message: error.message, client: null }
  }
}

3. Inside initializeEvents update the following

  checkIfEventisEnabled('qr')
    .then(_ => {
      client.on('qr', (qr) => {
        triggerWebhook(sessionWebhook, sessionId, 'qr', { qr })
        // eslint-disable-next-line no-undef
        resolve(qr)
      })
    })
    .catch(error => {
      // eslint-disable-next-line no-undef
      reject(error)
    })

**Comment by Adityasundawa** [comment]
not working, my qrCodePromise is undifened

**Comment by Adityasundawa** [comment]
@deepakvshinde

**Comment by avoylenko** [comment]
@chrishubert it seems like no one is willing to get the QR code from the webhook data. What do you think if we implement the `{{baseUrl}}/session/qr/:sessionid` endpoint to get it from there anytime?

**Comment by avoylenko** [comment]
@Adityasundawa `{{baseUrl}}/session/qr/:sessionid` and `{{baseUrl}}/session/qr/:sessionid/image` endpoints were added. You can use them to get the code.

**Comment by chrishubert** [comment]
@avoylenko maybe we can even change the main README accordingly, since this one confuses many people upfront

**Comment by avoylenko** [comment]
@chrishubert gonna update the README with necessary info to make it clean

**Comment by KushX** [comment]
> @Adityasundawa `{{baseUrl}}/session/qr/:sessionid` and `{{baseUrl}}/session/qr/:sessionid/image` endpoints were added. You can use them to get the code.

Resulting QR shows as:
{
    "success": true,
    "qr": "2@dwayVr........+sXhaI3eI=,1"
}

What language/encoding is the "qr" in? I'd assume Base64 or something, but just can't figure it out.
