### ISSUE TITLE
Session not connected despite loading of chats complete

### ISSUE THREAD

**Issue by ninoppp** [chrishubert/whatsapp-api#85]

**Comment by ninoppp** [comment]
ups, wanted to clarify: I've followed the quickstart guide, etc. After scanning the qr code, phone lists session as active (at least for a moment), message_log.txt says chats are loaded 100%, but http://localhost:3000/client/getContacts/ABCD still says "session not connected". Do you know what I'm doing wrong?

**Comment by ninoppp** [comment]
> > ups, wanted to clarify: I've followed the quickstart guide, etc. After scanning the qr code, phone lists session as active (at least for a moment), message_log.txt says chats are loaded 100%, but http://localhost:3000/client/getContacts/ABCD still says "session not connected". Do you know what I'm doing wrong?
> 
> Is your session id ABCD? whatever session you start you have to assign it an ID. You can also turn on Swagger if you haven't yet, really helps. My first time using and i could get it to work

It is ABCD (i copy pasted from the quickstart guide). Also, I'm a bit lost: I've enabled Swagger in .env, but /api-docs gives me `Cannot GET /api-docs` ?

**Comment by RuanFernandes** [comment]
> > Is your session id ABCD? whatever session you start you have to assign it an ID. You can also turn on Swagger if you haven't yet, really helps. My first time using and i could get it to work
> 
> It is ABCD (i copy pasted from the quickstart guide). Also, I'm a bit lost: I've enabled Swagger in .env, but /api-docs gives me `Cannot GET /api-docs` ?
> 
> edit: i also don't get any success message in the terminal after scanning the qr code

Are you running by docker, or the project source itself? I could make it work on docker here, all i changed was swagger env in docker-compose.yml, then i just executed `docker-compose up -d` and did a GET on /session/start then connected by QR code in docker terminal. It doesn't show a message in terminal for me after i scanned, but still works.

**Comment by ninoppp** [comment]
hmm okay, I got swagger to work. I'm using docker-compose. However, I still initiate a session, scan the qr code, and get   "message": "session_not_connected" when checking... don't get what I'm doing wrong

**Comment by chrishubert** [comment]
This is strange, it should work "out of the box" - can you possible try with another number?

**Comment by ninoppp** [comment]
actually, I thiink it got fixed in an update a few weeks back, did a docker pull and now it works.
