### ISSUE TITLE
Question regarding terminateInactiveSessions in production

### ISSUE THREAD

**Issue by ubeyou** [chrishubert/whatsapp-api#90]
Hi there, thanks for the amazing build. Am running well but need some feedbacks on the production.

for Production, it stated
Run periodically the /api/terminateInactiveSessions endpoint to prevent useless sessions to take up space and resources

in My Case, I'm only running 1 whatsapp instance using 1 session-id. Send message occasionally (probably 1-2 message per day).
Do I have to run that periodically?

At the moment, I only started the instance once, and will keep running unless server restart or so.

**Comment by avoylenko** [comment]
I see no reason why you should run the endpoint in your case. It makes sense only if you have multiple running instances.

**Comment by chrishubert** [comment]
Agreed with @avoylenko - if you are in control of your sessions, there is no such need.
When handling multiple sessions, this may be required as the disconnected sessions are eating up space on your disk for no reasons
